#设置端口号
server:
  port: 9999
#数据库驱动
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #数据库连接地址
    url: jdbc:mysql://localhost:3306/db_authority_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    #数据库用户名
    username: root
    #数据库密码
    password: 824008
    #JSON日期格式化
    jackson:
      date-format: yyyy-MM-dd
      #JSON日期格式化设置时区为上海
      time-zone: Asia/Shanghai
    #日期格式化
    mvc:
      format:
        date: yyyy-MM-dd
        date-time: yyyy-MM-dd HH:mm:ss

  redis:
    host: 112.124.3.50 #阿里云
    port: 6379
    database: 2
    timeout: 10000
    #自定义属性
    expire: 60000
#加载映射文件
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #设置别名
  type-aliases-package: com.song.entity
  #全局逻辑删除的实体字段名
  global-config:
    db-config:
      logic-delete-field: isDelete
      #逻辑删除值，默认为1
      logic-delete-value: 1
      #逻辑未删除值，默认为0
      logic-not-delete-value: 0
#显示日志
logging:
  level:
    com:
      song:
        dao: debug
#jwt配置
#密钥
jwt:
  secret: com.song
  #过期时间
  expiration: 1800000

#登录请求地址(自定义)
request:
  login:
    url: /api/user/login


